name: build
on: [pull_request, push]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'microsoft'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build artifacts
        run: ./gradlew build
      - name: Capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
      - if: ${{ contains(github.event.head_commit.message, 'release-') }}
        name: Release artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.head_commit.message }}